services:
  - type: web
    name: arila
    env: node
    buildCommand: "npm --prefix client install && npm --prefix client run build && npm --prefix server install && npm --prefix server run build"
    startCommand: "npm --prefix server start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
